name: Test Workflow

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:[manual-trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Run Script and Print content
        run: echo "Hello. This is the first workflow using SA and PAT !!!"
   
